apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
  {{- include "transmission.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- toJson .Values.transmission.settings | nindent 4 }}
