apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission-chart.fullname" . }}
  labels:
  {{- include "transmission-chart.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- toJson .Values.transmission | nindent 4 }}
