apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
  {{- include "transmission.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "transmission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "transmission.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "transmission.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: settings
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.jqImage.repository }}:{{ .Values.jqImage.tag }}
          imagePullPolicy: {{ .Values.jqImage.pullPolicy }}
          command:
            - sh
            - -c
            - |
          {{- .Files.Get "init-settings.sh" | trim | nindent 14 }}
          env:
            - name: TARGET
              value: /config/settings.json
            - name: FROM
              value: /var/run/configs/transmission/settings.json
            - name: WHITELIST
              value: /tmp/whitelist.json
            - name: WHITELIST_JSON
              value: >-
                {"rpc-host-whitelist-enabled":false,"rpc-whitelist-enabled":false}
          volumeMounts:
            - name: static-settings
              mountPath: /var/run/configs/transmission
              readOnly: true
            - name: transmission-config
              subPath: {{ .Values.transmission.configPersistentVolume.subPath }}
              mountPath: /config
              readOnly: false
      containers:
        - name: transmission
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
            - name: torrent-tcp
              containerPort: 51413
              protocol: TCP
            - name: torrent-udp
              containerPort: 51413
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: FILE__USER
              value: /var/run/secrets/transmission/{{ .Values.transmission.userSecretKey }}
            - name: FILE__PASS
              value: /var/run/secrets/transmission/{{ .Values.transmission.passSecretKey }}
          {{- if .Values.environment }}
          {{- toYaml .Values.environment | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: auth-secret
              mountPath: /var/run/secrets/transmission
              readOnly: true
            - name: transmission-config
              subPath: {{ .Values.transmission.configPersistentVolume.subPath }}
              mountPath: /config
              readOnly: false
            - name: transmission-downloads
              subPath: {{ .Values.transmission.downloadsPersistentVolume.subPath }}
              mountPath: /downloads
              readOnly: false
            - name: transmission-watch
              subPath: {{ .Values.transmission.watchPersistentVolume.subPath }}
              mountPath: /watch
              readOnly: false
        {{- if .Values.metrics.enabled }}
        - image: metalmatze/transmission-exporter
          name: metrics
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 30Mi
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          env:
            - name: TRANSMISSION_ADDR
              value: "http://localhost:9091"
            - name: TRANSMISSION_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.transmission.userSecretKey }}
                  name: {{ include "transmission.fullname" . }}
            - name: TRANSMISSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.transmission.passSecretKey }}
                  name: {{ include "transmission.fullname" . }}
            - name: WEB_PATH
              value: "/metrics"
            - name: WEB_ADDR
              value: ":{{ .Values.metrics.port }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: static-settings
          configMap:
            name: {{ include "transmission.fullname" . }}
        - name: auth-secret
          secret:
            secretName: {{ include "transmission.fullname" . }}
        - name: transmission-config
          {{ if .Values.transmission.configPersistentVolume.claimName -}}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.configPersistentVolume.claimName }}
          {{- else -}}
          emptyDir: { }
        {{- end }}
        - name: transmission-downloads
          {{ if .Values.transmission.downloadsPersistentVolume.claimName -}}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.downloadsPersistentVolume.claimName }}
          {{- else -}}
          emptyDir: { }
        {{- end }}
        - name: transmission-watch
          {{ if .Values.transmission.watchPersistentVolume.claimName -}}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.watchPersistentVolume.claimName }}
          {{- else -}}
          emptyDir: { }
  {{- end }}
