apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transmission-chart.fullname" . }}
  labels:
  {{- include "transmission-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "transmission-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "transmission-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "transmission-chart.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: settings
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.jqImage.repository }}:{{ .Values.jqImage.tag }}
          imagePullPolicy: {{ .Values.jqImage.pullPolicy }}
          command:
            - sh
            - -c
            - |
              jq -s '.[0] * .[1]' /config/settings.json /var/run/configs/transmission/settings.json > /tmp/settings.json
              cp /tmp/settings.json /config/settings.json
              # TODO
              cat /config/settings.json
          volumeMounts:
            - name: static-settings
              mountPath: /var/run/configs/transmission
              readOnly: true
            - name: transmission-config
              subPath: {{ .Values.transmission.configPersistentVolume.subPath }}
              mountPath: /config
              readOnly: false
      containers:
        - name: transmission
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
            - name: torrent-tcp
              containerPort: 51413
              protocol: TCP
            - name: torrent-udp
              containerPort: 51413
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: FILE__USER
              value: /var/run/secrets/transmission/{{ .Values.transmission.userSecretKey }}
            - name: FILE__PASS
              value: /var/run/secrets/transmission/{{ .Values.transmission.passSecretKey }}
          {{- if .Values.environment }}
          {{- toYaml .Values.environment | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: auth-secret
              mountPath: /var/run/secrets/transmission
              readOnly: true
            - name: transmission-config
              subPath: {{ .Values.transmission.configPersistentVolume.subPath }}
              mountPath: /config
              readOnly: false
            - name: transmission-downloads
              subPath: {{ .Values.transmission.downloadsPersistentVolume.subPath }}
              mountPath: /downloads
              readOnly: false
            - name: transmission-watch
              subPath: {{ .Values.transmission.watchPersistentVolume.subPath }}
              mountPath: /watch
              readOnly: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: static-settings
          configMap:
            name: {{ include "transmission-chart.fullname" . }}
        - name: auth-secret
          secret:
            secretName: {{ include "transmission-chart.fullname" . }}
        - name: transmission-config
          {{ if .Values.transmission.configPersistentVolume.claimName -}}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.configPersistentVolume.claimName }}
          {{- else -}}
          emptyDir: { }
        {{- end }}
        - name: transmission-downloads
          {{ if .Values.transmission.downloadsPersistentVolume.claimName -}}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.downloadsPersistentVolume.claimName }}
          {{- else -}}
          emptyDir: { }
        {{- end }}
        - name: transmission-watch
          {{ if .Values.transmission.watchPersistentVolume.claimName -}}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.watchPersistentVolume.claimName }}
          {{- else -}}
          emptyDir: { }
  {{- end }}
