{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
  {{- include "transmission.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - honorLabels: true
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      port: metrics
      path: /metrics
      {{- if.Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
  {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
  {{- end }}
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
  {{- include "transmission.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
