apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission-chart.fullname" . }}
  labels:
  {{- include "transmission-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.torrentPort }}
      targetPort: torrent-tcp
      protocol: TCP
      name: torrent-tcp
    - port: {{ .Values.service.torrentPort }}
      targetPort: torrent-udp
      protocol: UDP
      name: torrent-udp
  selector:
  {{- include "transmission-chart.selectorLabels" . | nindent 4 }}
